---
title: "GeocomputationR"
author: "Walter Chanava"
date: "4/11/2020"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    fig_caption: true
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = T,
  message = F,
  error = F,
  fig.align = 'center',
  warning = F
)
```

# Paquetes

```{r}
library(sf) # simple features
# library(raster)
# library(spData)
library(dplyr)
library(tmap)
library(rstatix)
```

# Datos

```{r}
data("world", package = "spData")
world
```

```{r}
class(world)
```

```{r}
# basic plot
plot(world)
```

# EDA

```{r}
# basic plot with filter
world %>% 
  filter(continent == "South America") %>% 
  plot()
```

```{r}
world_LE65 <- world %>% 
  filter(lifeExp > 65) %>% 
  select(name_long, lifeExp) %>% 
  arrange(desc(lifeExp)) 

world_LE65
```

```{r}
world %>% 
  st_drop_geometry() %>% 
  get_summary_stats(gdpPercap)
```

```{r}

```

## Mapa estatico de esperanza de vida

```{r}
tm_shape(world_LE65) +
  tm_borders() +
  tm_fill("lifeExp", breaks = c(65, 75, 85))
```

## Mapa interactivo de esperanza de vida

```{r}
tmap_mode("view")

map_world_LE65 <- tm_shape(world_LE65) +
  tm_borders() +
  tm_fill("lifeExp", breaks = c(65, 75, 85), alpha = .5)

map_world_LE65
```
